"""Canonical notebook cells, stamped into every v2 notebook by `scripts/stamp_notebooks.py` and verified by
`scripts/audit_notebooks.py` (a hand-edited or outdated copy is reported). Edit the text HERE, bump
`casmi.workspace.versions.BOOTSTRAP_CELL_VERSION`, then re-stamp the notebooks.

BOOTSTRAP_CELL must be self-contained: it runs before the repository exists, so it cannot import casmi. It contains
no double quotes and no backslashes (asserted below), so it embeds verbatim in notebook JSON.
"""
from casmi.workspace.versions import BOOTSTRAP_CELL_VERSION

BOOTSTRAP_MARKER_PREFIX = "# >>> CASMI BOOTSTRAP"
BOOTSTRAP_MARKER = f"{BOOTSTRAP_MARKER_PREFIX} {BOOTSTRAP_CELL_VERSION} (generated by scripts/stamp_notebooks.py; do not edit by hand)"

_TEMPLATE = '''{{MARKER}}
# mount Drive -> env roots -> clone if missing, else fetch + checkout + pull --ff-only -> drop stale casmi modules -> src on sys.path
import importlib, os, subprocess, sys
from pathlib import Path
IN_COLAB = 'google.colab' in sys.modules
if IN_COLAB:
    from google.colab import drive
    drive.mount('/content/drive')
DRIVE_ROOT = Path(os.environ.setdefault('ENVEDA_DRIVE_ROOT', '/content/drive/MyDrive/EnvedaCASMI'))
REPO_ROOT = Path(os.environ.setdefault('ENVEDA_REPO_ROOT', '/content/Enveda'))
os.environ.setdefault('ENVEDA_SCRATCH_DIR', '/content/enveda_work')
BRANCH = os.environ.setdefault('ENVEDA_BRANCH', 'main')
SYNC_REPO = os.environ.get('ENVEDA_SYNC_REPO', '1' if IN_COLAB else '0') == '1'  # outside Colab the working tree is used as is
GITHUB_REPO = 'mybenkhadda/enveda-kaggle'


def _git(*args):
    r = subprocess.run(['git', '-C', str(REPO_ROOT), *args], capture_output=True, text=True)
    if r.returncode != 0:
        cmd = ' '.join(args)
        raise RuntimeError(f'git {cmd} failed in {REPO_ROOT}: {r.stderr.strip()} | Fix: discard local edits inside the clone '
                           f'(git -C {REPO_ROOT} stash) or delete {REPO_ROOT}, then re-run this cell; source lives on GitHub only.')
    return r.stdout.strip()


if SYNC_REPO:
    token = None
    if IN_COLAB:
        try:
            from google.colab import userdata
            token = userdata.get('GITHUB_TOKEN')  # optional Colab secret (private repository)
        except Exception:
            token = None
    url = f'https://{token}@github.com/{GITHUB_REPO}.git' if token else f'https://github.com/{GITHUB_REPO}.git'
    if not (REPO_ROOT / '.git').exists():
        r = subprocess.run(['git', 'clone', '--branch', BRANCH, url, str(REPO_ROOT)], capture_output=True, text=True)
        if r.returncode != 0:
            err = r.stderr.replace(token, '***') if token else r.stderr
            raise RuntimeError(f'git clone of {GITHUB_REPO} failed: {err.strip()} | Fix: check the GITHUB_TOKEN Colab secret / network.')
    else:
        _git('fetch', 'origin', BRANCH)
        _git('checkout', BRANCH)
        _git('pull', '--ff-only', 'origin', BRANCH)
if not (REPO_ROOT / 'src' / 'casmi' / 'workspace' / 'versions.py').exists():
    raise RuntimeError(f'{REPO_ROOT} has no src/casmi/workspace/versions.py: the source is OLDER than this notebook. '
                       f'Fix: push the bootstrap/artifact-registry refactor to GitHub {BRANCH}, restart the runtime, re-run this cell.')
for _m in [m for m in list(sys.modules) if m == 'casmi' or m.startswith('casmi.')]:
    del sys.modules[_m]  # after a pull: never mix old and new source in one kernel
importlib.invalidate_caches()
if str(REPO_ROOT / 'src') not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / 'src'))
os.environ['ENVEDA_BOOTSTRAP_CELL'] = '{{VERSION}}'
_head = _git('log', '-1', '--format=%h %s') if (REPO_ROOT / '.git').exists() else 'no git (uploaded copy)'
print(f'source {REPO_ROOT} @ {_head} | drive {DRIVE_ROOT} | colab {IN_COLAB} | synced {SYNC_REPO}')'''

BOOTSTRAP_CELL = _TEMPLATE.replace("{{MARKER}}", BOOTSTRAP_MARKER).replace("{{VERSION}}", BOOTSTRAP_CELL_VERSION)
assert '"' not in BOOTSTRAP_CELL and "\\" not in BOOTSTRAP_CELL, "bootstrap cell must embed verbatim in notebook JSON"


def bootstrap_cell_version(cell_source):
    """Version string from a bootstrap cell's marker line, or None if the cell is not a bootstrap cell."""
    first = cell_source.lstrip().split("\n", 1)[0]
    if not first.startswith(BOOTSTRAP_MARKER_PREFIX):
        return None
    rest = first[len(BOOTSTRAP_MARKER_PREFIX):].strip()
    return rest.split(" ", 1)[0] if rest and not rest.startswith("(") else "casmi-v2-bootstrap-1"
